### ISSUE TITLE
16S copy number correction

### ISSUE THREAD

**Issue by mruehlemann** [yumyai/MetGEMs#5]
Hi!

I am not entirely sure whether 16S rRNA gene copy number corrections are performed automatically as part of the markp workflow. Looking at the code i get the idea that it probably is, however it would be great if you could comment on this.

Thank you!
Malte

**Comment by mruehlemann** [comment]
I dug a little deeper and please correct me if I'm wrong:
it seems that the datasets **should** include copy number corrections based on genus/species level assignments as defined in the anumber.**tsv** file which are supposed to be part of the tar-files included for all the models. however, inside the tar-files there are files called anumber.**txt** - so they are not automatically read.

**Comment by yumyai** [comment]
Hi mruehlemann,

Thank you for your report.  I will look into your pull request. 

btw.
Based on my test. including 16s gene copy number to the calculation does not really impact overall performance of the prediction (not in a significantly amount at least). Also, the number of 16s are usually a predicted one so it is not that reliable to being with. I still glad that you look into this and fix this though.


Thank you very much.

Preecha
